version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=Backend1
      - POSTGRES_USER=Backend1_user
      - POSTGRES_PASSWORD=Backend1_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data
volumes:
  db-data: